"""many to many

Revision ID: 1d49db5c0178
Revises: d149ff37a91a
Create Date: 2020-04-04 19:45:38.326569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d49db5c0178'
down_revision = 'd149ff37a91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userroles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userroles_rolename'), 'userroles', ['rolename'], unique=True)
    op.create_table('user_role_as',
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['userroles.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role_as')
    op.drop_index(op.f('ix_userroles_rolename'), table_name='userroles')
    op.drop_table('userroles')
    # ### end Alembic commands ###
