"""addedDateTime2

Revision ID: 3c82a3567984
Revises: c1c5a63cfc08
Create Date: 2020-07-06 21:23:37.394717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c82a3567984'
down_revision = 'c1c5a63cfc08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nlprecords', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nlprecords', 'created_at')
    # ### end Alembic commands ###
