"""AddingIndexs

Revision ID: 987f51b458c0
Revises: 3c82a3567984
Create Date: 2020-10-09 16:13:23.965030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987f51b458c0'
down_revision = '3c82a3567984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_nlprecords_created_at'), 'nlprecords', ['created_at'], unique=False)
    op.create_index(op.f('ix_nlprecords_input_text'), 'nlprecords', ['input_text'], unique=False)
    op.create_index(op.f('ix_nlprecords_output_text'), 'nlprecords', ['output_text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nlprecords_output_text'), table_name='nlprecords')
    op.drop_index(op.f('ix_nlprecords_input_text'), table_name='nlprecords')
    op.drop_index(op.f('ix_nlprecords_created_at'), table_name='nlprecords')
    # ### end Alembic commands ###
