"""addedDateTime

Revision ID: c1c5a63cfc08
Revises: 1d49db5c0178
Create Date: 2020-07-06 21:23:04.698660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c5a63cfc08'
down_revision = '1d49db5c0178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nlprecords', 'created_at')
    op.drop_column('nlprecords', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nlprecords', sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('nlprecords', sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
