"""updated nlprecords

Revision ID: d149ff37a91a
Revises: d160ebfafaea
Create Date: 2020-04-03 21:50:52.221123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd149ff37a91a'
down_revision = 'd160ebfafaea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nlprecords', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('nlprecords', sa.Column('updated_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nlprecords', 'updated_at')
    op.drop_column('nlprecords', 'created_at')
    # ### end Alembic commands ###
