"""added nlprecords

Revision ID: d160ebfafaea
Revises: f2f14adbf9f6
Create Date: 2020-04-03 21:43:41.306815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd160ebfafaea'
down_revision = 'f2f14adbf9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nlprecords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nlprecords')
    # ### end Alembic commands ###
